services:
  ext-img-cache:
    build: .
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ../files/ext_backends.conf:/etc/nginx/includes/ext_backends.conf:ro
      - ../files/redirects.conf:/etc/nginx/includes/redirects.conf:ro
      - img_cache:/var/cache/nginx
    networks:
      - dokploy-network

volumes:
  img_cache:

networks:
  dokploy-network:
    external: true
