
services:
  ext-img-cache:
    image: ghcr.io/iflixer-brazil/ext-img-cache:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../files/ext_backends.conf:/etc/nginx/includes/ext_backends.conf:ro
      - ../files/redirects.conf:/etc/nginx/includes/redirects.conf:ro
      - img_cache:/var/cache/nginx
    networks:
      - dokploy-network

    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: stop-first
        parallelism: 1

volumes:
  img_cache:

networks:
  dokploy-network:
    external: true
